# site settings
title: Julian Møller
description: ""

timezone: Europe/Copenhagen

date_format: "%b %-d, %Y"

latest_posts_num: 10

defaults:
  -
    scope: { path: "", type: "page" }
    values:
      layout: "sidebar"
  -
    scope: { path: "", type: "post" }
    values: { layout: "post" }

# Build settings
destination: _build
markdown: kramdown
permalink: pretty
permalink: /:year/:title.html
safe: true
