# site settings
title: Julian Møller
description: ""

url: "http://www.jumoel.com"
baseurl: "/"

timezone: Europe/Copenhagen

date_format: "%b %-d, %Y"

email: "contact-jumoel-com@julianmoeller.dk"
username:
  twitter: jumoel
  github: jumoel

latest_posts_num: 10

defaults:
  -
    scope: { path: "", type: "pages" }
    values:
      layout: "sidebar"
  -
    scope: { path: "", type: "posts" }
    values: { layout: "post" }

# Build settings
destination: _build
markdown: kramdown
permalink: /:year/:title.html

# Conform to GitHub Pages defaults
safe: true
lsi: false
